type: google.api.Service
config_version: 3

http:
  rules:
    - selector: diabetesproto.AuthService.Signin
      post: "/v1/auth/signin"
      body: "*"
    - selector: diabetesproto.AuthService.Signup
      post: "/v1/auth/signup"
      body: "*"
    - selector: diabetesproto.AuthService.Logout
      delete: "/v1/auth/logout"
    - selector: diabetesproto.AuthService.Auth
      get: "/v1/auth"

    - selector: diabetesproto.UserService.GetUserByEmail
      get: "/v1/user/{Email}"
    - selector: diabetesproto.UserService.GetAllUsers
      get: "/v1/user"

    - selector: diabetesproto.PredictionService.SavePrediction
      post: "/v1/prediction"
      body: "*"
    - selector: diabetesproto.PredictionService.GetAllPredictionsByUserId
      get: "/v1/prediction/{UserId}"
    - selector: diabetesproto.PredictionService.DeletePredictionById
      delete: "/v1/prediction/{Id}"