version: '3.8'

services:
  diabetes-user-mc-db:
    image: postgres:15
    container_name: diabetes-user-mc-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - microservices_network

  diabetes-mc-user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diabetes-mc-user
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - AUTH_MICROSERVICE_URL=${AUTH_MICROSERVICE_URL}
      - SERVICE_URL=${SERVICE_URL}
    depends_on:
      - diabetes-user-mc-db
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    networks:
      - microservices_network

networks:
  microservices_network:
    external: true

volumes:
  postgres_data:
